global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#us'
