global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#us'
