---
version: '3.3'
services:
  mongo_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/${UI_IMG}:${UI_VER}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/${POST_IMG}:${POST_VER}
    networks:
      - back_net
      - front_net

  comment:
    image: ${USERNAME}/${COMMENT_IMG}:${COMMENT_VER}
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${USERNAME}/${PROMETHEUS_IMG}:${PROMETHEUS_VER}
    ports:
      - '9090:9090'
    networks:
      - back_net
      - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.0
    user: root
    ports:
      - '9100:9100'
    networks:
      - back_net
      - front_net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

volumes:
  post_db:

networks:
  back_net:
  front_net:
