---
version: '3.3'
services:
  mongo_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/${UI_IMG}:${UI_VER}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/${POST_IMG}:${POST_VER}
    networks:
      - back_net
      - front_net

  comment:
    image: ${USERNAME}/${COMMENT_IMG}:${COMMENT_VER}
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${USERNAME}/${PROMETHEUS_IMG}:${PROMETHEUS_VER}
    volumes:
      - prometheus_data:/var/lib/prometheus
    ports:
      - '9090:9090'
    networks:
      - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.0
    user: root
    ports:
      - '9100:9100'
    networks:
      - front_net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  mongodb_exporter:
    image: ${USERNAME}/mongodb_exporter:latest
    command:
      - '-mongodb.uri=mongodb://mongo_db:27017'
    ports:
      - '9001:9001'
    networks:
      - back_net
      - front_net

  blackbox:
    image: prom/blackbox-exporter:master
    ports:
      - '9115:9115'
    networks:
      - front_net

  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.35.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - front_net

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - front_net

  alertmanager:
    image: ${USER_NAME}/alertmanager:latest
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      - front_net

volumes:
  post_db:
  prometheus_data:
  grafana_data:

networks:
  back_net:
  front_net:
