version: '3.3'
services:
  mongo_db:
    env_file: .env
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
  ui:
    env_file: .env
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      front_net:
        aliases:
          - ui
  post:
    env_file: .env
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post
  comment:
    env_file: .env
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment

  prometheus:
    image: ${USERNAME}/prometheus:${PROMETHEUS_VERSION}
    ports:
      - '9090:9090'
    networks:
      back_net:
      front_net:

volumes:
  post_db:

networks:
  back_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.2.0/24"
  front_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.1.0/24"
